In [20]:
import pandas as pd

In [21]:
import numpy as np

In [22]:
df = pd.read_csv('diabetic_data.csv')

In [23]:
print(df.shape)

(101766, 50)

In [25]:
df.drop('encounter_id', axis=1, inplace=True)

In [38]:
print("Dataset after dropping 'encounter_id':")
print (df.head)

Dataset after dropping 'encounter_id':
<bound method NDFrame.head of         patient_nbr             race  gender      age weight  \
0           8222157        Caucasian  Female   [0-10)      ?
1          55629189        Caucasian  Female  [10-20)      ?
2          86047875  AfricanAmerican  Female  [20-30)      ?
3          82442376        Caucasian    Male  [30-40)      ?
4          42519267        Caucasian    Male  [40-50)      ?
...             ...              ...     ...      ...    ...
101761    100162476  AfricanAmerican    Male  [70-80)      ?
101762     74694222  AfricanAmerican  Female  [80-90)      ?
101763     41088789        Caucasian    Male  [70-80)      ?
101764     31693671        Caucasian  Female  [80-90)      ?
101765    175429310        Caucasian    Male  [70-80)      ?

        admission_type_id  discharge_disposition_id  admission_source_id  \
0                       6                        25                    1
1                       1                         1                    7
2                       1                         1                    7
3                       1                         1                    7
4                       1                         1                    7
...                   ...                       ...                  ...
101761                  1                         3                    7
101762                  1                         4                    5
101763                  1                         1                    7
101764                  2                         3                    7
101765                  1                         1                    7

        time_in_hospital payer_code  ... citoglipton  insulin  \
0                      1          ?  ...          No       No
1                      3          ?  ...          No       Up
2                      2          ?  ...          No       No
3                      2          ?  ...          No       Up
4                      1          ?  ...          No   Steady
...                  ...        ...  ...         ...      ...
101761                 3         MC  ...          No     Down
101762                 5         MC  ...          No   Steady
101763                 1         MC  ...          No     Down
101764                10         MC  ...          No       Up
101765                 6          ?  ...          No       No

        glyburide-metformin  glipizide-metformin  glimepiride-pioglitazone  \
0                        No                   No                        No
1                        No                   No                        No
2                        No                   No                        No
3                        No                   No                        No
4                        No                   No                        No
...                     ...                  ...                       ...
101761                   No                   No                        No
101762                   No                   No                        No
101763                   No                   No                        No
101764                   No                   No                        No
101765                   No                   No                        No

        metformin-rosiglitazone  metformin-pioglitazone change diabetesMed  \
0                            No                      No     No          No
1                            No                      No     Ch         Yes
2                            No                      No     No         Yes
3                            No                      No     Ch         Yes
4                            No                      No     Ch         Yes
...                         ...                     ...    ...         ...
101761                       No                      No     Ch         Yes
101762                       No                      No     No         Yes
101763                       No                      No     Ch         Yes
101764                       No                      No     Ch         Yes
101765                       No                      No     No          No

       readmitted
0               0
1               0
2               0
3               0
4               0
...           ...
101761          0
101762          0
101763          0
101764          0
101765          0

[101766 rows x 49 columns]>

In [39]:
df.replace('?', np.nan, inplace=True)
print("Dataset after replacing '?' with NaN:")
print(df.head())

Dataset after replacing '?' with NaN:
   patient_nbr             race  gender      age weight  admission_type_id  \
0      8222157        Caucasian  Female   [0-10)    NaN                  6
1     55629189        Caucasian  Female  [10-20)    NaN                  1
2     86047875  AfricanAmerican  Female  [20-30)    NaN                  1
3     82442376        Caucasian    Male  [30-40)    NaN                  1
4     42519267        Caucasian    Male  [40-50)    NaN                  1

   discharge_disposition_id  admission_source_id  time_in_hospital payer_code  \
0                        25                    1                 1        NaN
1                         1                    7                 3        NaN
2                         1                    7                 2        NaN
3                         1                    7                 2        NaN
4                         1                    7                 1        NaN

   ... citoglipton  insulin  glyburide-metformin  glipizide-metformin  \
0  ...          No       No                   No                   No
1  ...          No       Up                   No                   No
2  ...          No       No                   No                   No
3  ...          No       Up                   No                   No
4  ...          No   Steady                   No                   No

   glimepiride-pioglitazone  metformin-rosiglitazone  metformin-pioglitazone  \
0                        No                       No                      No
1                        No                       No                      No
2                        No                       No                      No
3                        No                       No                      No
4                        No                       No                      No

  change diabetesMed readmitted
0     No          No          0
1     Ch         Yes          0
2     No         Yes          0
3     Ch         Yes          0
4     Ch         Yes          0

[5 rows x 49 columns]

In [40]:
df['readmitted'] = df['readmitted'].apply(lambda x: 1 if x == '<30' else 0)
print("Data sample after converting 'readmitted':")
display(df.head())

Data sample after converting 'readmitted':

,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,...,No,No,No,No,No,No,No,No,No,0
1,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,0
2,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,...,No,No,No,No,No,No,No,No,Yes,0
3,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,0
4,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,0

In [43]:
print(df.columns)

Index(['patient_nbr', 'race', 'gender', 'age', 'weight', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'payer_code', 'medical_specialty', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [44]:
missing_percentages = df.isnull().sum() / len(df) * 100

In [45]:
columns_to_drop = missing_percentages[missing_percentages > 90].index.tolist()

In [46]:
df.drop(columns=columns_to_drop, axis=1, inplace=True)

In [47]:
print("Remaining columns after dropping those with >90% missing values:")
print(df.columns)

Remaining columns after dropping those with >90% missing values:
Index(['patient_nbr', 'race', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'payer_code', 'medical_specialty', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'A1Cresult', 'metformin', 'repaglinide',
       'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide',
       'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone',
       'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide',
       'examide', 'citoglipton', 'insulin', 'glyburide-metformin',
       'glipizide-metformin', 'glimepiride-pioglitazone',
       'metformin-rosiglitazone', 'metformin-pioglitazone', 'change',
       'diabetesMed', 'readmitted'],
      dtype='object')